version: '3.1'

services:
  # RDBMS config
#  db:
#    container_name: db_postgres
#    image: postgres
#    restart: always
#    ports:
#      - 5432:5432
#    environment:
#      - POSTGRES_USER=boilerplate
#      - POSTGRES_PASSWORD=boilerplate
  # Application config for RDBMS
#  app:
#    image: 'spring-boot-boilerplate:latest'
#    build:
#      context: .
#    container_name: app
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/boilerplate
#      - SPRING_DATASOURCE_USERNAME=boilerplate
#      - SPRING_DATASOURCE_PASSWORD=boilerplate
#      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  # NoSQL DB
  mongo:
    image: mongo:4.4
    container_name: mongo
    hostname: mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=pass
      - MONGO_INITDB_DATABASE=db
      - MONGO_DB_USERNAME=user
      - MONGO_DB_PASSWORD=pass
  app:
    image: 'spring-boot-boilerplate:latest'
    build:
      context: .
    container_name: app
    depends_on:
      - mongo
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_HOST=mongo
      - SPRING_DATA_MONGODB_PORT=27017
      - SPRING_DATA_MONGODB_USERNAME=user
      - SPRING_DATA_MONGODB_PASSWORD=pass
      - SPRING_DATA_MONGODB_DATABASE=db
